# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    "name" : "Export multiple BoM Structure Excel",
    "author": "OMAX Informatics",
    "version": "15.0.1.0",
    "website": "https://www.omaxinformatics.com",
    "category": "MRP",
    "description" : """
        This App allows to export multiple BoM Structure in a excel file with separate sheet.
    """,
    "summary": """
        Export BoM Structure in excel,bom,sub-bom,export hierarchy of BOM and product cost  Excel bom, Download bom, download bom excel,App to download multiple bom selection,App to download multiple boms selection,  Download BOM in seperate excel sheet,Download multi BOM in seperate excel sheet, Download report bom structure,  Export report bom structure, Export Bom and cost report, Export product and cost report, Excel,  download hierarchy of BOM and product cost, export hierarchy of BOM and product cost report, export hierarchy of BOM in excel,  Export multi BOM, Export multiple BOm, Export multiple bom in excel, export hierarchy of BOM and product report,  Bill of material Export,Bill of material Excel, multiple bom export, multiple bom export excel,BoM Structure in a excel file,  BOm in BoM Structure in a excel file,export multiple BoM Structure,BoM Structure in a excel file,  BoM Structure in a excel file with separate sheet, excel sheet,
Excel中导出BOM结构,BOM,子BOM,导出BOM和产品成本的层次结构 Excel中导出BOM,下载BOM,下载BOM excel,下载多个BOM选择的应用程序,下载多个BOM选择的应用程序,在单独的excel表中下载BOM,在单独的excel表中下载多个BOM,下载报告BOM结构,导出报告BOM结构,导出BOM和成本报告,导出产品和成本报告,Excel,下载BOM和产品成本的层次结构、  在excel中导出BOM层次结构, 导出多个BOM, 导出多个BOM, 在excel中导出多个BOM, 导出BOM和产品报告的层次结构, 物料清单导出,物料清单Excel, 多个BOM导出, 多个BOM导出excel, 在excel文件中的BOM结构, 在excel文件中的BOM结构, 导出多个BOM结构, 在excel文件中的BOM结构, 在excel文件中的BOM结构与单独的表, excel表、导出BOM层次结构和产品成本报告、
Export BOM structuur in excel,bom,sub-bom,export hiërarchie van BOM en productkosten Excel bom, Download bom, download bom excel,App om meerdere boms selectie te downloaden,App om meerdere boms selectie te downloaden, Download BOM in aparte excel sheet,Download multi BOM in aparte excel sheet, Download rapport bom structuur, Export rapport bom structuur, Export Bom en kostenrapport, Export product en kostenrapport, Excel, download hiërarchie van BOM en productkosten,  exporteer hiërarchie van BOM in excel, exporteer multi BOM, exporteer multiple BOm, exporteer multiple bom in excel, exporteer hiërarchie van BOM en productrapport, Bill of material export, Bill of material Excel, multiple bom export, multiple bom export excel, BoM Structure in een excel bestand, BOm in BoM Structure in een excel bestand, exporteer multiple BoM Structure, BoM Structure in een excel bestand, BoM Structure in een excel bestand met apart blad, excel blad, exporthiërarchie van BOM en productkostenrapport,
Exporter la structure de la nomenclature en excel,bom,sub-bom,exporter la hiérarchie de la nomenclature et le coût du produit Excel bom, Télécharger bom, télécharger bom excel,App pour télécharger la sélection multiple de bom,App pour télécharger la sélection multiple de boms, Télécharger la nomenclature dans une feuille excel séparée,Télécharger multi BOM dans une feuille excel séparée, Télécharger le rapport sur la structure de la nomenclature, Exporter le rapport sur la structure de la nomenclature, Exporter le rapport sur la nomenclature et le coût, Exporter le rapport sur le produit et le coût, Excel, télécharger la hiérarchie de la nomenclature et le coût du produit,  Exporter la hiérarchie des nomenclatures en excel, Exporter plusieurs nomenclatures, Exporter plusieurs BOm, Exporter plusieurs bom en excel, Exporter la hiérarchie des nomenclatures et le rapport produit, Exporter la nomenclature, Exporter la nomenclature en excel, Exporter plusieurs bom, Exporter plusieurs bom en excel, Structure BoM dans un fichier excel, Structure BoM dans un fichier excel, Exporter plusieurs structures BoM, Structure BoM dans un fichier excel, Structure BoM dans un fichier excel avec feuille séparée, feuille excel, Exporter la hiérarchie des nomenclatures et le rapport coût du produit,
Export BoM Struktur in excel,bom,sub-bom,export Hierarchie von BOM und Produktkosten Excel bom, Download bom, download bom excel,App zum Download von mehreren bom Auswahl,App zum Download von mehreren boms Auswahl, Download BOM in separaten Excel-Blatt,Download Multi BOM in separaten Excel-Blatt, Download Bericht bom Struktur, Export Bericht bom Struktur, Export Bom und Kosten Bericht, Export Produkt-und Kostenbericht, Excel, Download Hierarchie von BOM und Produktkosten,  Export Hierarchie der BOM in Excel, Export mehrere BOM, Export mehrere BOm, Export mehrere bom in excel, Export Hierarchie der BOM und Produkt-Bericht, Bill of Material Export, Bill of Material Excel, mehrere bom export, mehrere bom export excel, BoM Struktur in einer excel-Datei, BOm in BoM Struktur in einer excel-Datei, export mehrere BoM Struktur, BoM Struktur in einer excel-Datei, BoM Struktur in einer excel-Datei mit separaten Blatt, excel-Blatt, Export Hierarchie der BOM und Produkt Kostenbericht,
Ekspor Struktur BoM di excel, bom, sub-bom, hirarki ekspor BOM dan biaya produk Bom excel, Unduh bom, unduh bom excel, Aplikasi untuk mengunduh beberapa pilihan bom, Aplikasi untuk mengunduh beberapa pilihan bom, Unduh BOM di lembar excel terpisah, Unduh multi BOM di lembar excel terpisah, Unduh struktur bom laporan, Ekspor struktur bom laporan, Ekspor Bom dan laporan biaya, Ekspor produk dan laporan biaya, Excel, unduh hirarki BOM dan biaya produk,  hirarki ekspor BOM di excel, Ekspor multi BOM, Ekspor beberapa BOm, Ekspor beberapa bom di excel, hirarki ekspor BOM dan laporan produk, Ekspor bill of material, Bill of material Excel, ekspor beberapa bom, ekspor beberapa bom excel, Struktur BoM dalam file excel, BOm dalam Struktur BoM dalam file excel, ekspor beberapa struktur BoM, Struktur BoM dalam file excel, Struktur BoM dalam file excel dengan lembar terpisah, lembar excel, hirarki ekspor BOM dan laporan biaya produk,
Esportazione Struttura BoM in excel, bom, sub-bom, esportazione gerarchia della distinta base e costo del prodotto Excel bom, Download bom, download bom excel, App per scaricare selezione multipla bom, App per scaricare selezione multipla bom, Download distinta base in foglio excel separato, Download multi distinta base in foglio excel separato, Download relazione struttura bom, Esportazione relazione bom, Esportazione relazione bom e costo, Esportazione relazione prodotto e costo, Excel, download gerarchia della distinta base e costo del prodotto,  Esportazione gerarchia della distinta base in excel, Esportazione multi distinta base, Esportazione multipla distinta base, Esportazione multipla distinta base in excel, Esportazione gerarchia distinta base e rapporto prodotto, Esportazione distinta base, Esportazione distinta base multipla, Esportazione distinta base multipla excel, Struttura distinta base in un file excel, Struttura distinta base in un file excel, Esportazione struttura distinta base multipla, Struttura distinta base in un file excel, Struttura distinta base in un file excel con foglio separato, foglio excel, Esportazione gerarchia distinta base e rapporto costo prodotto,
ExcelでBOM構造をエクスポート,ボム,サブボム,BOMと製品コストのエクスポート階層 Excelのボム, ボムをダウンロード, ボムエクセルをダウンロード,複数のボム選択をダウンロードするアプリ,複数のボム選択をダウンロードするアプリ, 別のExcelシートでBOMをダウンロード,別のExcelシートでマルチBOMをダウンロード, ダウンロードレポート ボム構造, エクスポートレポート ボム構造, エクスポートボムとコストレポート, エクスポート製品とコストレポート, エクセル, BOMと製品コストのダウンロード階層、  エクセルでBOMのエクスポート階層, 複数のBOMをエクスポート, 複数のBOmをエクスポート, エクセルで複数のボムをエクスポート, BOMと製品レポートのエクスポート階層, 部品表のエクスポート,部品表のエクセル, 複数のボムのエクスポート, 複数のボムエクスポートエクセル, エクセルファイル内のBoM構造, エクセルファイル内のBoM構造, 複数のBoM構造をエクスポート, エクセルファイル内のBoM構造, 別のシート、エクセルシートでBoM構造, BOMと製品コストレポートのエクスポート階層、
엑셀에서 BOM 구조 내보내기, 봄, 하위 봄, BOM 및 제품 비용 엑셀 봄 내보내기, 봄 다운로드, 봄 엑셀 다운로드, 여러 봄 선택을 다운로드하는 앱, 여러 봄 선택을 다운로드하는 앱, 별도의 엑셀 시트에서 BOM 다운로드, 별도의 엑셀 시트에서 멀티 BOM 다운로드, 보고서 봄 구조 다운로드, 보고서 봄 구조 내보내기, BOM 및 비용 보고서 내보내기, 제품 및 비용 보고서, Excel, BOM 및 제품 비용의 계층 구조를 다운로드합니다,  엑셀에서 BOM 계층 구조 내보내기, 다중 BOM 내보내기, 여러 BOm 내보내기, 엑셀에서 여러 BOM 내보내기, BOM 및 제품 보고서 내보내기, 자재 명세서 내보내기, 자재 명세서 엑셀, 여러 BOM 내보내기, 여러 BOM 내보내기 엑셀, 엑셀 파일의 BoM 구조, 엑셀 파일의 BoM 구조, 엑셀 파일의 BoM 구조, 별도의 시트가있는 엑셀 파일의 BoM 구조, 엑셀 시트, BOM 및 제품 비용 보고서의 계층 구조를 내 보냅니다,
Eksporter BoM-struktur i Excel, bom, underbom, eksporter hierarki av BOM og produktkostnad Excel bom, Last ned bom, last ned bom excel, App for å laste ned flere bomvalg, App for å laste ned flere bomvalg, Last ned BOM i separat excelark, Last ned flere BOM i separat excelark, Last ned rapport bomstruktur, Eksporter rapport bomstruktur, Eksporter bom- og kostnadsrapport, Eksporter produkt- og kostnadsrapport, Excel, last ned hierarki av BOM og produktkostnad,  eksporter hierarki av BOM i excel, Eksporter flere BOM, Eksporter flere BOm, Eksporter flere bom i excel, eksporter hierarki av BOM og produktrapport, Bill of material Export,Bill of material Excel, flere bom eksport, flere bom eksport excel,BoM Structure i en excel-fil, BOm i BoM Structure i en excel-fil,eksporter flere BoM Structure,BoM Structure i en excel-fil, BoM Structure i en excel-fil med separat ark, excel-ark,eksporter hierarki av BOM og produktkostnadsrapport,
Eksportuj strukturę BoM w Excelu, bom, sub-bom, eksportuj hierarchię BOM i koszt produktu Excel bom, Pobierz bom, pobierz bom excel, Aplikacja do pobierania wielu wyborów bom, Aplikacja do pobierania wielu wyborów boms, Pobierz BOM w oddzielnym arkuszu Excela, Pobierz wiele BOM w oddzielnym arkuszu Excela, Pobierz strukturę bom raportu, Eksportuj strukturę bom raportu, Eksportuj Bom i raport kosztów, Eksportuj raport produktów i kosztów, Excel, pobierz hierarchię BOM i koszt produktu,  eksport hierarchii BOM w excel, eksport wielu BOM, eksport wielu BOm, eksport wielu bom w excel, eksport hierarchii BOM i raportu produktu, eksport zestawienia materiałów, eksport zestawienia materiałów Excel, eksport wielu bom, eksport wielu bom excel, struktura BoM w pliku excel, BOm w strukturze BoM w pliku excel, eksport wielu struktur BoM, struktura BoM w pliku excel, struktura BoM w pliku excel z oddzielnym arkuszem, arkusz excel, eksport hierarchii BOM i raportu kosztów produktu,
Exportar estrutura de BOM em excel,bom,sub-bom,exportar hierarquia de BOM e custo de produto Excel bom,Descarregar bom,descarregar bom excel,App para descarregar seleção de múltiplos bom,App para descarregar seleção de múltiplos boms,Descarregar BOM em folha separada de excel,Descarregar multi BOM em folha separada de excel,Descarregar relatório estrutura de BOM,Exportar relatório estrutura de BOM,Exportar BOM e relatório de custo,Exportar produto e relatório de custo,Excel,descarregar hierarquia de BOM e custo de produto,  exportar hierarquia de lista técnica em excel, Exportar lista técnica múltipla, Exportar lista técnica múltipla, Exportar lista técnica múltipla em excel, Exportar hierarquia de lista técnica e relatório de produto, Exportar lista técnica, Lista técnica Excel, Exportar lista técnica múltipla, Exportar lista técnica múltipla em excel, Exportar estrutura de lista técnica em um arquivo excel, Exportar estrutura de lista técnica em um arquivo excel, Exportar estrutura de lista técnica múltipla, Exportar estrutura de lista técnica em um arquivo excel, Exportar estrutura de lista técnica em um arquivo excel com folha separada, Folha excel, Exportar hierarquia de lista técnica e relatório de custo de produto,
Exportar estrutura de BOM em Excel, BOM, sub-BOM, Exportar hierarquia de BOM e custo de produto, Excel, Baixar BOM, Baixar BOM Excel, Aplicativo para baixar seleção de várias BOMs, Aplicativo para baixar seleção de várias BOMs, Baixar BOM em planilha separada do Excel, Baixar várias BOM em planilha separada do Excel, Baixar relatório de estrutura de BOM, Exportar relatório de estrutura de BOM, Exportar relatório de BOM e custo, Exportar relatório de produto e custo, Excel, Baixar hierarquia de BOM e custo de produto,  exportar hierarquia de lista técnica em excel, exportar lista técnica múltipla, exportar lista técnica múltipla, exportar lista técnica múltipla em excel, exportar hierarquia de lista técnica e relatório de produto, exportar lista técnica, exportar lista técnica em excel, exportar lista técnica múltipla, exportar lista técnica múltipla em excel, exportar estrutura de lista técnica em arquivo excel, exportar estrutura de lista técnica múltipla, exportar estrutura de lista técnica em arquivo excel, exportar estrutura de lista técnica em arquivo excel com planilha separada, planilha excel, exportar hierarquia de lista técnica e relatório de custo de produto,
Экспорт структуры БОМ в excel,bom,sub-bom,экспорт иерархии БОМ и стоимости продукции Excel bom,скачать bom,скачать bom excel,приложение для загрузки выбора нескольких bom,приложение для загрузки выбора нескольких bom,скачать БОМ в отдельном листе excel,скачать несколько БОМ в отдельном листе excel,скачать отчет о структуре БОМ,экспорт отчета о структуре БОМ,экспорт отчета о БОМ и стоимости,экспорт отчета о продукции и стоимости,Excel,скачать иерархию БОМ и стоимость продукции,  экспорт иерархии BOM в excel, экспорт нескольких BOM, экспорт нескольких BOM, экспорт нескольких BOM в excel, экспорт иерархии BOM и отчета о стоимости продукции, Bill of material Export,Bill of material Excel, multiple bom export, multiple bom export excel, BoM Structure in a excel file, BOM in BoM Structure in a excel file, экспорт нескольких BoM Structure, BoM Structure in a excel file, BoM Structure in a excel file with separate sheet, excel sheet,экспорт иерархии BOM и отчета о стоимости продукции,
Exportar estructura de lista de materiales en excel,bom,sub-bom,exportar jerarquía de lista de materiales y coste del producto Excel bom, Download bom, download bom excel,App to download multiple bom selection,App to download multiple boms selection, Download BOM in seperate excel sheet,Download multi BOM in seperate excel sheet, Download report bom structure, Export report bom structure, Export Bom and cost report, Export product and cost report, Excel, download jerarquía de lista de materiales y coste del producto,  exportar jerarquia de lista de materiales en excel, Exportar multi lista de materiales, Exportar multi lista de materiales, Exportar multi lista de materiales en excel, Exportar jerarquia de lista de materiales e informe de producto, Exportar lista de materiales,Exportar lista de materiales en excel, Exportar multi lista de materiales en excel, Exportar multi lista de materiales en excel, Exportar multi lista de materiales en excel, Exportar jerarquia de lista de materiales e informe de producto, Exportar lista de materiales en excel, Exportar lista de materiales en excel, Exportar multi lista de materiales en excel, Exportar multi lista de materiales en excel, Exportar jerarquia de lista de materiales e informe de coste de producto,
Excel'de BoM Yapısını Dışa Aktar, bom, alt bom, BOM ve ürün maliyeti hiyerarşisini dışa aktar Excel bom, Bom indir, bom excel indir, Çoklu bom seçimini indirmek için uygulama, Çoklu bom seçimini indirmek için uygulama, Ayrı excel sayfasında BOM indir, Ayrı excel sayfasında çoklu BOM indir, Rapor bom yapısını indir, Rapor bom yapısını dışa aktar, Bom ve maliyet raporunu dışa aktar, Ürün ve maliyet raporunu dışa aktar, Excel, BOM ve ürün maliyeti hiyerarşisini indir,  excel'de BOM hiyerarşisini dışa aktar, Çoklu BOM dışa aktar, Çoklu BOm dışa aktar, Excel'de çoklu bom dışa aktar, BOM ve ürün raporunun hiyerarşisini dışa aktar, Malzeme Listesi Dışa Aktarma, Malzeme Listesi Excel, çoklu bom dışa aktarma, çoklu bom dışa aktarma excel, Bir excel dosyasında BoM Yapısı, Bir excel dosyasında BoM Yapısında BOm, Çoklu BoM Yapısını dışa aktar, Bir excel dosyasında BoM Yapısı, Ayrı sayfalı bir excel dosyasında BoM Yapısı, excel sayfası, BOM ve ürün maliyet raporunun hiyerarşisini dışa aktar,
Exportera BoM-struktur i excel,bom,sub-bom,export hierarki av BOM och produktkostnad Excel bom, Ladda ner bom, ladda ner bom excel,App för att ladda ner flera bomval,App för att ladda ner flera boms val, Ladda ner BOM i separat excelark,Ladda ner flera BOM i separat excelark, Ladda ner rapport bomstruktur, Exportera rapport bomstruktur, Exportera Bom och kostnadsrapport, Exportera produkt- och kostnadsrapport, Excel, ladda ner hierarki av BOM och produktkostnad,  exportera hierarki av BOM i excel, Exportera multi BOM, Exportera flera BOm, Exportera flera bom i excel, exportera hierarki av BOM och produktrapport, Bill of material Export,Bill of material Excel, flera bom export, flera bom export excel,BoM Struktur i en excel-fil, BOm i BoM Struktur i en excel-fil, exportera flera BoM Struktur,BoM Struktur i en excel-fil, BoM Struktur i en excel-fil med separat ark, excel ark,export hierarki av BOM och produktkostnadsrapport,
Excel'de BoM Yapısını Dışa Aktar, bom, alt bom, BOM ve ürün maliyeti hiyerarşisini dışa aktar Excel bom, Bom indir, bom excel indir, Çoklu bom seçimini indirmek için uygulama, Çoklu bom seçimini indirmek için uygulama, Ayrı excel sayfasında BOM indir, Ayrı excel sayfasında çoklu BOM indir, Rapor bom yapısını indir, Rapor bom yapısını dışa aktar, Bom ve maliyet raporunu dışa aktar, Ürün ve maliyet raporunu dışa aktar, Excel, BOM ve ürün maliyeti hiyerarşisini indir,  excel'de BOM hiyerarşisini dışa aktar, Çoklu BOM dışa aktar, Çoklu BOm dışa aktar, Excel'de çoklu bom dışa aktar, BOM ve ürün raporunun hiyerarşisini dışa aktar, Malzeme Listesi Dışa Aktarma, Malzeme Listesi Excel, çoklu bom dışa aktarma, çoklu bom dışa aktarma excel, Bir excel dosyasında BoM Yapısı, Bir excel dosyasında BoM Yapısında BOm, Çoklu BoM Yapısını dışa aktar, Bir excel dosyasında BoM Yapısı, Ayrı sayfalı bir excel dosyasında BoM Yapısı, excel sayfası, BOM ve ürün maliyet raporunun hiyerarşisini dışa aktar,
Експорт структури специфікацій в Excel, bom, sub-bom, експорт ієрархії специфікацій і вартості продукції Excel bom, Завантажити bom, Завантажити bom Excel, Додаток для завантаження декількох виділених bom, Додаток для завантаження декількох виділених bom, Завантажити специфікацію на окремому аркуші Excel, Завантажити декілька специфікацій на окремому аркуші Excel, Завантажити структуру звіту bom, Експорт структури звіту bom, Експорт специфікації та звіту про вартість, Експорт звіту про вартість продукції та звіту про вартість, Excel, завантажити ієрархію специфікацій та вартості продукції,  експорт ієрархії специфікацій в Excel, експорт кількох специфікацій, експорт кількох специфікацій, експорт кількох специфікацій в Excel, експорт ієрархії специфікацій і звіту про продукцію, експорт специфікацій, експорт специфікацій Excel, експорт кількох специфікацій, експорт кількох специфікацій Excel, структура специфікацій в Excel, структура специфікацій в Excel, експорт кількох специфікацій в Excel, структура специфікацій в Excel, структура специфікацій в Excel з окремим аркушем, аркуш Excel, експорт ієрархії специфікацій і звіту про собівартість продукту,
تصدير بنية BoM في Excel ، bom ، sub-bom ، التسلسل الهرمي لتصدير BOM وتكلفة المنتج Excel bom ، تنزيل bom ، تنزيل bom excel ، تطبيق لتنزيل مجموعة bom ، تطبيق لتنزيل مجموعة bom ، تنزيل BOM في ورقة Excel منفصلة ، قم بتنزيل قائمة مكونات الصنف المتعددة في ورقة Excel المنفصلة ، وتنزيل بنية bom للتقرير ، وبنية تقرير bom للتصدير ، وتقرير Bom للتصدير وتقرير التكلفة ، وتقرير تصدير المنتج والتكلفة ، و Excel ، وتنزيل التسلسل الهرمي لقائمة المواد وتكلفة المنتج ، والتسلسل الهرمي لتصدير قائمة مكونات الصنف في Excel ، وتصدير قائمة مكونات الصنف المتعددة ، تصدير عدة بوم ، تصدير بوم في إكسل ، تصدير التسلسل الهرمي لقائمة المواد وتقرير المنتج ، تصدير فاتورة المواد ، فاتورة المواد إكسل ، تصدير بوم متعدد ، إكسل تصدير بوم متعدد ، هيكل بوم في ملف إكسل ، بوم في هيكل بوم في ملف Excel ، وتصدير بنية BoM متعددة ، وهيكل BoM في ملف Excel ، و BoM Structure في ملف Excel مع ورقة منفصلة ، وورقة Excel ، وتسلسل هرمي لتصدير BOM وتقرير تكلفة المنتج ،
صادرات ساختار BoM در اکسل، بوم، ساب بوم، سلسله مراتب صادرات BOM و هزینه محصول اکسل بوم، دانلود بوم، دانلود بوم اکسل، برنامه برای دانلود انتخاب چند بوم، برنامه دانلود انتخاب چند بوم، دانلود BOM در برگه اکسل جداگانه، دانلود مولتی BOM در برگه اکسل جداگانه، دانلود گزارش ساختار bom، ساختار گزارش صادرات، گزارش Bom و هزینه صادرات، گزارش محصول و هزینه صادرات، اکسل، دانلود سلسله مراتب BOM و هزینه محصول، سلسله مراتب صادرات BOM در اکسل، صادرات چند BOM , صادرات BOm چندگانه, صادرات چند بوم در اکسل, سلسله مراتب صادراتی BOM و گزارش محصول, صدور صورت حساب مواد, صورتحساب مواد اکسل, صادرات چندگانه بوم, صادرات اکسل چندگانه بوم, ساختار BoM در یک فایل اکسل, BOm در ساختار BoM در یک فایل اکسل، صادرات چندین ساختار BoM، ساختار BoM در یک فایل اکسل، ساختار BoM در یک فایل اکسل با برگه جداگانه، برگه اکسل، سلسله مراتب صادرات BOM و گزارش هزینه محصول،
	""",
    "depends" : [
        "stock", "mrp"],
    "external_dependencies": {
        "python": ["xlwt"]
    },
    "data": [
        "security/ir.model.access.csv",
        "wizard/export_mrp_bom_structure_excel.xml",
    ],
    "demo": [],
    "test": [],
    "images": ["static/description/banner.png",],
    "assets": {
    },
    "license": "OPL-1",
    "currency":"EUR",
    "price": 25.0,
    "installable" : True,
    "auto_install" : False,
    "application" : True,
    "pre_init_hook": "pre_init_check",
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
